/* Generated By:JavaCC: Do not edit this line. NoWhiteConstants.java */
package by.bsu.project.parser.nowhite;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NoWhiteConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int hashLine = 1;
  /** RegularExpression Id. */
  int number = 2;
  /** RegularExpression Id. */
  int newLine = 3;
  /** RegularExpression Id. */
  int space = 4;
  /** RegularExpression Id. */
  int tab = 5;
  /** RegularExpression Id. */
  int others = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"#line \"",
    "<number>",
    "<newLine>",
    "\" \"",
    "\"\\t\"",
    "<others>",
  };

}
