/* Generated By:JavaCC: Do not edit this line. CommentConstants.java */
package by.bsu.project.javacc.parser.comment;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CommentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int singleLineComment = 1;
  /** RegularExpression Id. */
  int formalComment = 5;
  /** RegularExpression Id. */
  int multiLineComment = 6;
  /** RegularExpression Id. */
  int endFormalOrMultiLineComment = 7;
  /** RegularExpression Id. */
  int newLine = 11;
  /** RegularExpression Id. */
  int hashLine = 12;
  /** RegularExpression Id. */
  int number = 13;
  /** RegularExpression Id. */
  int word = 14;
  /** RegularExpression Id. */
  int subword = 15;
  /** RegularExpression Id. */
  int space = 16;
  /** RegularExpression Id. */
  int others = 17;
  /** RegularExpression Id. */
  int character_literal = 18;
  /** RegularExpression Id. */
  int string_literal = 19;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int inSingleLineComment = 1;
  /** Lexical state. */
  int inFormalOrMultiLineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"//\"",
    "<token of kind 2>",
    "<token of kind 3>",
    "<token of kind 4>",
    "<formalComment>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "<newLine>",
    "\"#line \"",
    "<number>",
    "<word>",
    "<subword>",
    "<space>",
    "<others>",
    "<character_literal>",
    "<string_literal>",
  };

}
