/* Generated By:JavaCC: Do not edit this line. CPPConstants.java */
package by.bsu.project.javacc.parser.cpp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CPPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int newLine = 1;
  /** RegularExpression Id. */
  int hashLine = 2;
  /** RegularExpression Id. */
  int singleLineComment = 3;
  /** RegularExpression Id. */
  int multiLineComment = 4;
  /** RegularExpression Id. */
  int endAnyMultiLineComment = 7;
  /** RegularExpression Id. */
  int GOTO = 9;
  /** RegularExpression Id. */
  int TYPE = 10;
  /** RegularExpression Id. */
  int AUTO = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CASE = 13;
  /** RegularExpression Id. */
  int CATCH = 14;
  /** RegularExpression Id. */
  int CLASS = 15;
  /** RegularExpression Id. */
  int CONTINUE = 16;
  /** RegularExpression Id. */
  int _DEFAULT = 17;
  /** RegularExpression Id. */
  int DELETE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int ENUM = 21;
  /** RegularExpression Id. */
  int EXTERN = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int FINALLY = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int FOR = 26;
  /** RegularExpression Id. */
  int FRIEND = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int IMPLEMENTS = 29;
  /** RegularExpression Id. */
  int IMPORT = 30;
  /** RegularExpression Id. */
  int INLINE = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int INTERFACE = 33;
  /** RegularExpression Id. */
  int NATIVE = 34;
  /** RegularExpression Id. */
  int NEW = 35;
  /** RegularExpression Id. */
  int NULL = 36;
  /** RegularExpression Id. */
  int PACKAGE = 37;
  /** RegularExpression Id. */
  int REDECLARED = 38;
  /** RegularExpression Id. */
  int REGISTER = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int SHORT = 41;
  /** RegularExpression Id. */
  int SIGNED = 42;
  /** RegularExpression Id. */
  int SIZEOF = 43;
  /** RegularExpression Id. */
  int STATIC = 44;
  /** RegularExpression Id. */
  int STRUCT = 45;
  /** RegularExpression Id. */
  int SUPER = 46;
  /** RegularExpression Id. */
  int SWITCH = 47;
  /** RegularExpression Id. */
  int THIS = 48;
  /** RegularExpression Id. */
  int THROW = 49;
  /** RegularExpression Id. */
  int TRUE = 50;
  /** RegularExpression Id. */
  int TRY = 51;
  /** RegularExpression Id. */
  int UNION = 52;
  /** RegularExpression Id. */
  int UNSIGNED = 53;
  /** RegularExpression Id. */
  int VIRTUAL = 54;
  /** RegularExpression Id. */
  int WHILE = 55;
  /** RegularExpression Id. */
  int MODIFIERS = 56;
  /** RegularExpression Id. */
  int IDENTIFIER = 57;
  /** RegularExpression Id. */
  int LETTER = 58;
  /** RegularExpression Id. */
  int DIGIT = 59;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 60;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 61;
  /** RegularExpression Id. */
  int HEX_LITERAL = 62;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 63;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 64;
  /** RegularExpression Id. */
  int EXPONENT = 65;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 66;
  /** RegularExpression Id. */
  int STRING_LITERAL = 67;
  /** RegularExpression Id. */
  int LPAREN = 68;
  /** RegularExpression Id. */
  int RPAREN = 69;
  /** RegularExpression Id. */
  int LBRACE = 70;
  /** RegularExpression Id. */
  int RBRACE = 71;
  /** RegularExpression Id. */
  int LBRACKET = 72;
  /** RegularExpression Id. */
  int RBRACKET = 73;
  /** RegularExpression Id. */
  int SEMICOLON = 74;
  /** RegularExpression Id. */
  int COMMA = 75;
  /** RegularExpression Id. */
  int DOT = 76;
  /** RegularExpression Id. */
  int QUESTIONMARK = 77;
  /** RegularExpression Id. */
  int ELLIPSIS = 78;
  /** RegularExpression Id. */
  int ASSIGN = 79;
  /** RegularExpression Id. */
  int GT = 80;
  /** RegularExpression Id. */
  int LT = 81;
  /** RegularExpression Id. */
  int BANG = 82;
  /** RegularExpression Id. */
  int TILDE = 83;
  /** RegularExpression Id. */
  int SCOPE = 84;
  /** RegularExpression Id. */
  int COLON = 85;
  /** RegularExpression Id. */
  int EQ = 86;
  /** RegularExpression Id. */
  int LE = 87;
  /** RegularExpression Id. */
  int GE = 88;
  /** RegularExpression Id. */
  int NE = 89;
  /** RegularExpression Id. */
  int SC_OR = 90;
  /** RegularExpression Id. */
  int SC_AND = 91;
  /** RegularExpression Id. */
  int INCR = 92;
  /** RegularExpression Id. */
  int DECR = 93;
  /** RegularExpression Id. */
  int PLUS = 94;
  /** RegularExpression Id. */
  int MINUS = 95;
  /** RegularExpression Id. */
  int STAR = 96;
  /** RegularExpression Id. */
  int SLASH = 97;
  /** RegularExpression Id. */
  int BIT_AND = 98;
  /** RegularExpression Id. */
  int BIT_OR = 99;
  /** RegularExpression Id. */
  int XOR = 100;
  /** RegularExpression Id. */
  int REM = 101;
  /** RegularExpression Id. */
  int SHIFT = 102;
  /** RegularExpression Id. */
  int POINTERTO = 103;
  /** RegularExpression Id. */
  int DOTSTAR = 104;
  /** RegularExpression Id. */
  int ARROWSTAR = 105;
  /** RegularExpression Id. */
  int PLUSASSIGN = 106;
  /** RegularExpression Id. */
  int MINUSASSIGN = 107;
  /** RegularExpression Id. */
  int STARASSIGN = 108;
  /** RegularExpression Id. */
  int SLASHASSIGN = 109;
  /** RegularExpression Id. */
  int ANDASSIGN = 110;
  /** RegularExpression Id. */
  int REMASSIGN = 111;
  /** RegularExpression Id. */
  int SHIFTASSIGN = 112;
  /** RegularExpression Id. */
  int others = 114;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int inSingleLineComment = 1;
  /** Lexical state. */
  int inAnyMultiLineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<newLine>",
    "\"#line \"",
    "\"//\"",
    "\"/*\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"*/\"",
    "<token of kind 8>",
    "\"goto\"",
    "<TYPE>",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"inline\"",
    "\"int\"",
    "\"interface\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"super\"",
    "\"switch\"",
    "\"this.\"",
    "\"throw\"",
    "\"true\"",
    "\"try\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"while\"",
    "<MODIFIERS>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"::\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "<SHIFT>",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "<ANDASSIGN>",
    "\"%=\"",
    "<SHIFTASSIGN>",
    "<token of kind 113>",
    "<others>",
  };

}
