/* Generated By:JavaCC: Do not edit this line. NormaliserConstants.java */
package by.bsu.project.parser.normaliser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NormaliserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 4;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 5;
  /** RegularExpression Id. */
  int BRACES = 6;
  /** RegularExpression Id. */
  int SEMICOLON = 7;
  /** RegularExpression Id. */
  int INC_OPT = 8;
  /** RegularExpression Id. */
  int NOT_OPT = 9;
  /** RegularExpression Id. */
  int OPERATOR = 10;
  /** RegularExpression Id. */
  int CAST = 11;
  /** RegularExpression Id. */
  int LITERAL = 12;
  /** RegularExpression Id. */
  int GAP = 13;
  /** RegularExpression Id. */
  int LINENO = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int SPACE = 16;
  /** RegularExpression Id. */
  int NEWLINE = 17;
  /** RegularExpression Id. */
  int DQUOTE = 18;
  /** RegularExpression Id. */
  int SQUOTE = 19;
  /** RegularExpression Id. */
  int DQUOTE_ESCAPE = 20;
  /** RegularExpression Id. */
  int SQUOTE_ESCAPE = 21;
  /** RegularExpression Id. */
  int OTHER = 22;
  /** RegularExpression Id. */
  int SINGLECOMMENT = 23;
  /** RegularExpression Id. */
  int MULTICOMMENTSTART = 24;
  /** RegularExpression Id. */
  int MULTICOMMENTEND = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"(\"",
    "\")\"",
    "<BRACES>",
    "\";\"",
    "<INC_OPT>",
    "<NOT_OPT>",
    "<OPERATOR>",
    "<CAST>",
    "<LITERAL>",
    "<GAP>",
    "\"#line \"",
    "<NUMBER>",
    "<SPACE>",
    "\"\\n\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\'\"",
    "<OTHER>",
    "\"//\"",
    "<MULTICOMMENTSTART>",
    "\"*/\"",
  };

}
